name: CI - Build & Push Docker Image

on:
  push:
    branches:
      - '**'
    paths:
      - 'app/**'
  workflow_dispatch:

permissions:
  contents: write

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REPO: "yaswanthmitta"
  IMAGE_NAME: multiapp-todo-app

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: CILinting 🧹
        run: echo "Running CI Linting..."

      - name: Source Code Analysis 🔍
        run: echo "Running Source Code Analysis..."
      
      - name: Software Component Analysis (SCA) 📦
        run: echo "Running SCA..."

      - name: Static Application Security Testing (SAST) 🔒
        run: echo "Running SAST..."

      - name: Build (.jar, etc.) 🛠️
        run: echo "Building application..."

      - name: Run Unit Tests ✅
        run: echo "Running unit tests..."

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Create Docker Image 🐳
        run: |
          IMAGE_TAG="${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          docker build -t $IMAGE_TAG -f ./app/Dockerfile ./app

      - name: Push Docker Image to Docker Hub 🚢
        run: |
          IMAGE_TAG="${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          docker push $IMAGE_TAG

      - name: Deploy into some cluster 🚀
        run: |
          echo "Deploying to a cluster..."

      - name: Dynamic Application Security Testing (DAST) 🛡️
        run: echo "Running DAST..."

      - name: Update and push deployment manifest
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          sed -i "s|image: ${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:.*|image: ${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }}|g" k8s/deployment.yaml
          
          git add k8s/deployment.yaml
          git diff --staged --quiet || git commit -m "chore: Update image tag to ${{ github.sha }} [skip ci]"
          git push
